# Site settings
name: 'Almanack'
description: 
meta_description: 
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'franklinhalfdollar.png'
  greetings: "Hello & Welcome."
favicon: '/favicon.ico'
baseurl: '/almanack'
production_url: 'https://walkercraig.github.io/almanack'
disqus: 
mailchimp_url: '//walkercraig.us11.list-manage.com/subscribe/post?u=b845f7d1807ad41b6c0437990&amp;id=7bd2f97cd8'
# Add your GA Tracking Id
ga_analytics: G-08CYSHEKGT

# Contact form settings
email: editor@almanack.blog
contact_page_description: "Feel free to contact us with any questions, concerns, or inquiries. You may also reach us by sending an email direct to the following address: editor at almanack dot blog."
thankyou_page_description: "Your message has been successfully sent. We will contact you soon!"

# Social links
twitter: 'almanackblog'
facebook: 'almanackblog'
instagram: 'almanackblog'

# Navigation
navigation:
  - text: Home
    url: /almanack
  - text: About
    url: /almanack/about
  - text: Commentary
    url: /almanack/tags/index.html#comment
  - text: Features
    url: /almanack/tags/index.html#features
  - text: Contact
    url: /almanack/contact
  - text: Shop
    url: https://www.bonfire.com/store/chicagojournal/
  - text: Donate
    url: /donate
  - text: Search
    url: /almanack/search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

remote_theme: royce
