# Site settings
name: 'Almanack'
description: 
meta_description: Almanack is an independent, subscriber-supported blog launched in 2024 as America approached its 250th year. Inspired by the tradition of American letters, it weaves past and present to enrich today’s conversation on American arts, business, lifestyle, politics, science, and sport.
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'franklinhalfdollar.png'
  greetings: "On Life, Liberty, and the Pursuit..."
favicon: '/favicon.ico'
url:  "https://www.almanack.blog"
baseurl: ''
production_url: 'https://walkercraig.github.io/almanack'
disqus: 
mailchimp_url: '//walkercraig.us11.list-manage.com/subscribe/post?u=b845f7d1807ad41b6c0437990&amp;id=7bd2f97cd8'
# Add your GA Tracking Id
ga_analytics: G-08CYSHEKGT

# Contact form settings
email: editor@almanack.blog
contact_page_description: "Feel free to contact us with any questions, concerns, or inquiries. You may also reach us by sending an email direct to the following address: editor at almanack dot blog."
thankyou_page_description: "Your message has been successfully sent. We will contact you soon!"

# Social links
twitter: 'almanackblog'
facebook: 'almanackblog'
instagram: 'almanackblog'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Commentary
    url: /tags/index.html#comment
  - text: Features
    url: /tags/index.html#features
  - text: Contact
    url: /contact
  - text: Shop
    url: https://www.bonfire.com/store/chicagojournal/
  - text: Donate
    url: /donate
  - text: Search
    url: /search

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

remote_theme: royce
